### ISSUE TITLE
Add winget to list of ways to download Orange

### ISSUE THREAD

**Issue by irgolic** [biolab/orange-hugo#203]
As is described in Orange's ![README](https://github.com/biolab/orange3/blob/master/README.md), I suppose this should be listed next to pip.

**Comment by ajdapretnar** [comment]
Winget is still in the preview stage as reported on the official website.
<img width="768" alt="Screen Shot 2020-11-06 at 11 01 26" src="https://user-images.githubusercontent.com/12524972/98359497-a1c8bc80-2028-11eb-8223-18a3e2462a9b.png">

Also, @thocevar warns about this in https://github.com/biolab/orange3/pull/4935#issuecomment-687029487.

I would wait with promoting winget until it is a fully-supported Windows package manager.

**Comment by irgolic** [comment]
Could we just add an 'experimental' label next to it? It seems sensible to include it on the website if it's in Orange3's README.

**Comment by thocevar** [comment]
We don't want to promote it on the website, at least not yet. It's on Github if someone wants it explicitly and knows how to use it. We are also not actively maintaining winget's repository. Instead, we are relying on the user who added Orange to winget to keep updating it there.

**Comment by ajdapretnar** [comment]
I will respectfully close this.
