### ISSUE TITLE
FAQ: redesign

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange-hugo#71]
I think we went too far in the last FAQ redesign (#32). Current design prevents any kind of scan-through of text. Also, the category buttons are so non-standard that is not that obvious that they are clickable.

I'd suggest some old boring structure such as:
- https://docs.python.org/3/faq/programming.html
- https://www.gimp.org/docs/userfaq.html

**Comment by ajdapretnar** [comment]
YouTube has a similar format to ours, but not quite: https://support.google.com/youtube/?hl=en-GB#topic=9257498
WhatsApp has a nice one, but you need to click to access all questions for a certain category: https://faq.whatsapp.com/
Tableau's is nice and clean, but also boring: https://www.tableau.com/support/faqs

I agree that our version of category buttons is not nice, but they are far from non-standard - many FAQ sites have category buttons. We need to come up with something that guides the user to the answer they are looking for, in whatever form that may be.

**Comment by markotoplak** [comment]
@ajdapretnar, I am fine with any of the solutions you mentioned.

Youtube makes it very clear that you can click on a category. We could copy this one.

But I like the other two even better, because I can scan through the questions.

**Comment by ajdapretnar** [comment]
I think I like Tableau's version the best. If we can make it a bit more, ekhm, juicy, them I am on board. 😁  🍊
