### ISSUE TITLE
Improve styling of individual widget pages

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange-hugo#89]
The current widget display is ugly and hard to read. It has very strange inwards alignment. Then, the text is too small, too wide and images too little.

Here the content is readable:
https://docs.biolab.si//3/visual-programming/widgets/data/datatable.html

And here it is not:
https://orange.biolab.si/widget-catalog/data/datatable/

It would be good if we could make the latter more like the former.

The widget documentation is linked with the webpage only at build time, therefore, for testing, you will need to extract the following archive into your orange-hugo folder:
https://drive.google.com/file/d/1A_c6vyhd4FdaWDy1sU2gbgrBmY8W4_Qa/view?usp=sharing

**Comment by ajdapretnar** [comment]
Agree, this is badly needed!

**Comment by markotoplak** [comment]
Duplicate of #100
