### ISSUE TITLE
Blog search sorts in a strange way

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange-hugo#94]
I tried searching for "education" but I get some old posts first. The order should be descending by the date.

**Comment by mitjapotocin** [comment]
Where are scripts located? I couldn’t find search.js in this repo.

**Comment by markotoplak** [comment]
static/js/ 

Hugo copies everything from static/ to the root folder.

**Comment by mitjapotocin** [comment]
I was thinking about removing the search button and displaying results, as the user types in.

**Comment by markotoplak** [comment]
It it can be responsive enough, it would be cool.

**Comment by mitjapotocin** [comment]
Search doesn’t work at all on localhost. What am I missing here?

**Comment by markotoplak** [comment]
Hmm, I do not know. Works for me on Ubuntu / Firefox 69. I tried with "carrots" and "education".

**Comment by NejcDebevec** [comment]
Blog search sorts by the relevance of the page.

**Comment by ajdapretnar** [comment]
What does it mean 'revelance'? 🤔 I mean how is the relevance determined?

**Comment by NejcDebevec** [comment]
@ajdapretnar The relevance is determined by occurrences of the search parameter in Title and Content and Keywords of the blog post. Each of those have a specific weight.
